image: "${ruby}"

cache:
  key: "${CI_COMMIT_REF_SLUG}-${ruby}"
  paths: [ "vendor/ruby", "gemfiles/vendor/ruby" ]

before_script:
  - ruby -v
  # Hack for docker images without `git` (e.g. jruby)
  - |
    if ! command -v git; then
      apt-get update && apt-get -y install git
    fi
  # HACK: ruby < 2.7 docker images have bundler < 2.0
  - gem install bundler
  - bundle config set path "vendor/ruby"
  - bundle config set without "development doc"
  - bundle install --jobs $(nproc)

# Rubocop ######################################################################

rubocop:
  stage:     test
  variables: { ruby: "ruby:2.5" }
  script:    bundle exec rubocop

# RSpec ########################################################################

rspec:
  stage:     test
  services:  [ "${redis}" ]
  variables: { REDIS_URL: "redis://redis:6379" }
  script:
    - bundle exec appraisal install --jobs $(nproc)
    - bundle exec appraisal rspec
  parallel:
    matrix:
      - redis:           [ "redis:4", "redis:5", "redis:6" ]
        ruby:            [ "ruby:2.5", "ruby:2.6", "ruby:2.7", "jruby:9.2" ]
        REDIS_NAMESPACE: [ "", "xxx" ]
