image: "${ruby}"

cache:
  key: "${CI_COMMIT_REF_SLUG}-${ruby}"
  paths: [ "vendor/ruby", "gemfiles/vendor/ruby" ]

before_script:
  - ruby -v
  - bundle config set path "vendor/ruby"
  - bundle config set without "development doc"
  - bundle install --jobs $(nproc)

# Rubocop ######################################################################

rubocop:
  stage:     test
  variables: { ruby: "ruby:2.5" }
  script:    bundle exec rubocop

# RSpec ########################################################################

rspec:
  stage:     test
  services:  [ "${redis}" ]
  variables: { REDIS_URL: "redis://redis:6379" }
  script:
    - bundle exec appraisal install --jobs $(nproc)
    - bundle exec appraisal rspec
  parallel:
    matrix:
      - redis:           [ "redis:4", "redis:5", "redis:6" ]
        ruby:            [ "ruby:2.5", "ruby:2.6", "ruby:2.7", "jruby:9.2" ]
        REDIS_NAMESPACE: [ "", "xxx" ]

# YARD #########################################################################

pages:
  stage:     deploy
  variables: { ruby: "ruby:2.7" }
  artifacts: { paths: [public] }
  before_script:
    - bundle config set without "development"
    - bundle install --jobs $(nproc)
  script:
    - bundle exec yard
    - mv doc public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
