image: "${ruby}"

cache:
  key: "${CI_COMMIT_REF_SLUG}-${ruby}"
  paths: [ "vendor/ruby", "gemfiles/vendor/ruby" ]

before_script:
  - ruby -v
  - bundle config set path "vendor/ruby"
  - bundle config set without "development doc"
  - bundle install --jobs $(nproc)

.test:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "web"'

# Rubocop ######################################################################

rubocop:
  extends:   .test
  variables: { ruby: "ruby:2.6" }
  script:    bundle exec rubocop

# RSpec ########################################################################

rspec:
  extends:   .test
  services:  [ "${redis}" ]
  variables: { REDIS_URL: "redis://redis:6379" }
  script:    scripts/ci-rspec
  parallel:
    matrix:
      - redis: [ "redis:4.0", "redis:5.0", "redis:6.0", "redis:6.2" ]
        ruby:  [ "ruby:2.6", "ruby:2.7", "ruby:3.0", "ruby:3.1" ]

# YARD #########################################################################

pages:
  stage:     deploy
  variables: { ruby: "ruby:3.1" }
  artifacts: { paths: [public] }
  before_script:
    - bundle config set without "development"
    - bundle install --jobs $(nproc)
  script:
    - bundle exec yard
    - mv doc public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
