image: "${ruby}"

cache:
  key: "${CI_COMMIT_REF_SLUG}-${ruby}"
  paths: [ "vendor/ruby", "gemfiles/vendor/ruby" ]

before_script:
  - ruby -v
  - bundle config set path "vendor/ruby"
  - bundle config set without "development doc"
  - bundle install --jobs $(nproc)

.test:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "web"'

# RSpec ########################################################################

rspec:
  extends:   .test
  services:  [ "${redis}" ]
  variables: { REDIS_URL: "redis://redis:6379" }
  script:
    - bundle exec appraisal install --jobs $(nproc)
    - REDIS_NAMESPACE="" bundle exec appraisal rspec
    - REDIS_NAMESPACE="xxx" bundle exec appraisal rspec
  parallel:
    matrix:
      - { ruby: "ruby:2.7",  redis: "redis:6", COVERAGE: "1" }
      - { ruby: "ruby:2.7",  redis: "redis:5" }
      - { ruby: "ruby:2.7",  redis: "redis:4" }
      - { ruby: "ruby:2.6",  redis: "redis:6" }
      - { ruby: "ruby:2.5",  redis: "redis:6" }
      - { ruby: "ruby:2.4",  redis: "redis:6" }
      - { ruby: "jruby:9.2", redis: "redis:6" }

# Rubocop ######################################################################

rubocop:
  extends:   .test
  variables: { ruby: "ruby:2.4" }
  script:    bundle exec rubocop

# YARD #########################################################################

pages:
  stage:     deploy
  variables: { ruby: "ruby:2.7" }
  artifacts: { paths: [public] }
  before_script:
    - bundle config set without "development"
    - bundle install --jobs $(nproc)
  script:
    - bundle exec yard
    - mv doc public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
