#!/usr/bin/env bash

set -ex

gemfiles=(
  "gemfiles/redis_4.2.x.gemfile"
  "gemfiles/redis_4.3.x.gemfile"
  "gemfiles/redis_4.4.x.gemfile"
)

for BUNDLE_GEMFILE in "${gemfiles[@]}"; do
  env BUNDLE_GEMFILE="${BUNDLE_GEMFILE}" bundle install
  env BUNDLE_GEMFILE="${BUNDLE_GEMFILE}" bundle exec rspec
  env BUNDLE_GEMFILE="${BUNDLE_GEMFILE}" REDIS_NAMESPACE="xxx" bundle exec rspec
done
